name: sustainability-gis

channels:
  - conda-forge

dependencies:
  - python=3.11.6
  - gitpython
  - git
  - jupyterlab=4.3.4
  - jupyterlab-git
  - access
  - contextily
  - dask
  - dask-ml
  - datashader
  - esda
  - geopandas
  - geojson
  - geoplot
  - geoviews
  - inequality
  - mapclassify
  - matplotlib
  - mesa
  - mgwr
  - momepy
  - movingpandas
  - networkx
  - openjdk
  - openpyxl
  - osmnx
  - palettable
  - pandana
  - pointpats
  - pyrosm
  - pysal
  - python-igraph
  - r5py.sampledata.helsinki>=0.1.1dev2
  - r5py.sampledata.sao_paulo>=0.1.1dev2
  - scipy
  - scikit-image
  - scikit-learn
  - scikit-mobility
  - segregation
  - simpy
  - spint
  - splot
  - spreg
  - statsmodels
  - seaborn
  - pandas
  - urbanaccess
  - nose
  - jinja2
  - pip
  - pip:
      - r5py==1.0.0.dev0
      - jupyterlab_myst
      - geostream
